# coding: utf-8

"""
    Bandwidth Dashboard REST API Documentation

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_accounts_account_id_available_npa_nxx_get(self):
        """
        Test case for accounts_account_id_available_npa_nxx_get

        
        """
        pass

    def test_accounts_account_id_available_numbers_get(self):
        """
        Test case for accounts_account_id_available_numbers_get

        
        """
        pass

    def test_accounts_account_id_bdrs_bdrid_file_get(self):
        """
        Test case for accounts_account_id_bdrs_bdrid_file_get

        
        """
        pass

    def test_accounts_account_id_bdrs_bdrid_get(self):
        """
        Test case for accounts_account_id_bdrs_bdrid_get

        
        """
        pass

    def test_accounts_account_id_bdrs_post(self):
        """
        Test case for accounts_account_id_bdrs_post

        
        """
        pass

    def test_accounts_account_id_billingreports_post(self):
        """
        Test case for accounts_account_id_billingreports_post

        
        """
        pass

    def test_accounts_account_id_billingreports_reportid_file_get(self):
        """
        Test case for accounts_account_id_billingreports_reportid_file_get

        
        """
        pass

    def test_accounts_account_id_billingreports_reportid_get(self):
        """
        Test case for accounts_account_id_billingreports_reportid_get

        
        """
        pass

    def test_accounts_account_id_discnumbers_get(self):
        """
        Test case for accounts_account_id_discnumbers_get

        
        """
        pass

    def test_accounts_account_id_discnumbers_totals_get(self):
        """
        Test case for accounts_account_id_discnumbers_totals_get

        
        """
        pass

    def test_accounts_account_id_disconnects_disconnectid_get(self):
        """
        Test case for accounts_account_id_disconnects_disconnectid_get

        
        """
        pass

    def test_accounts_account_id_disconnects_disconnectid_notes_get(self):
        """
        Test case for accounts_account_id_disconnects_disconnectid_notes_get

        
        """
        pass

    def test_accounts_account_id_disconnects_disconnectid_notes_post(self):
        """
        Test case for accounts_account_id_disconnects_disconnectid_notes_post

        
        """
        pass

    def test_accounts_account_id_disconnects_get(self):
        """
        Test case for accounts_account_id_disconnects_get

        
        """
        pass

    def test_accounts_account_id_disconnects_post(self):
        """
        Test case for accounts_account_id_disconnects_post

        
        """
        pass

    def test_accounts_account_id_dldas_get(self):
        """
        Test case for accounts_account_id_dldas_get

        
        """
        pass

    def test_accounts_account_id_dldas_orderid_get(self):
        """
        Test case for accounts_account_id_dldas_orderid_get

        
        """
        pass

    def test_accounts_account_id_dldas_orderid_history_get(self):
        """
        Test case for accounts_account_id_dldas_orderid_history_get

        
        """
        pass

    def test_accounts_account_id_dldas_orderid_put(self):
        """
        Test case for accounts_account_id_dldas_orderid_put

        
        """
        pass

    def test_accounts_account_id_dldas_post(self):
        """
        Test case for accounts_account_id_dldas_post

        
        """
        pass

    def test_accounts_account_id_e911s_get(self):
        """
        Test case for accounts_account_id_e911s_get

        
        """
        pass

    def test_accounts_account_id_e911s_orderid_get(self):
        """
        Test case for accounts_account_id_e911s_orderid_get

        
        """
        pass

    def test_accounts_account_id_e911s_orderid_history_get(self):
        """
        Test case for accounts_account_id_e911s_orderid_history_get

        
        """
        pass

    def test_accounts_account_id_e911s_post(self):
        """
        Test case for accounts_account_id_e911s_post

        
        """
        pass

    def test_accounts_account_id_external_tns_get(self):
        """
        Test case for accounts_account_id_external_tns_get

        
        """
        pass

    def test_accounts_account_id_external_tns_orderid_get(self):
        """
        Test case for accounts_account_id_external_tns_orderid_get

        
        """
        pass

    def test_accounts_account_id_external_tns_post(self):
        """
        Test case for accounts_account_id_external_tns_post

        
        """
        pass

    def test_accounts_account_id_get(self):
        """
        Test case for accounts_account_id_get

        
        """
        pass

    def test_accounts_account_id_hosts_get(self):
        """
        Test case for accounts_account_id_hosts_get

        
        """
        pass

    def test_accounts_account_id_inservice_numbers_get(self):
        """
        Test case for accounts_account_id_inservice_numbers_get

        
        """
        pass

    def test_accounts_account_id_inservice_numbers_tn_get(self):
        """
        Test case for accounts_account_id_inservice_numbers_tn_get

        
        """
        pass

    def test_accounts_account_id_inservice_numbers_totals_get(self):
        """
        Test case for accounts_account_id_inservice_numbers_totals_get

        
        """
        pass

    def test_accounts_account_id_lidbs_get(self):
        """
        Test case for accounts_account_id_lidbs_get

        
        """
        pass

    def test_accounts_account_id_lidbs_lidbid_get(self):
        """
        Test case for accounts_account_id_lidbs_lidbid_get

        
        """
        pass

    def test_accounts_account_id_lidbs_post(self):
        """
        Test case for accounts_account_id_lidbs_post

        
        """
        pass

    def test_accounts_account_id_line_option_orders_post(self):
        """
        Test case for accounts_account_id_line_option_orders_post

        
        """
        pass

    def test_accounts_account_id_lnpchecker_post(self):
        """
        Test case for accounts_account_id_lnpchecker_post

        
        """
        pass

    def test_accounts_account_id_lsrorders_get(self):
        """
        Test case for accounts_account_id_lsrorders_get

        
        """
        pass

    def test_accounts_account_id_lsrorders_orderid_get(self):
        """
        Test case for accounts_account_id_lsrorders_orderid_get

        
        """
        pass

    def test_accounts_account_id_lsrorders_orderid_history_get(self):
        """
        Test case for accounts_account_id_lsrorders_orderid_history_get

        
        """
        pass

    def test_accounts_account_id_lsrorders_orderid_notes_get(self):
        """
        Test case for accounts_account_id_lsrorders_orderid_notes_get

        
        """
        pass

    def test_accounts_account_id_lsrorders_orderid_notes_post(self):
        """
        Test case for accounts_account_id_lsrorders_orderid_notes_post

        
        """
        pass

    def test_accounts_account_id_lsrorders_orderid_put(self):
        """
        Test case for accounts_account_id_lsrorders_orderid_put

        
        """
        pass

    def test_accounts_account_id_lsrorders_post(self):
        """
        Test case for accounts_account_id_lsrorders_post

        
        """
        pass

    def test_accounts_account_id_orders_get(self):
        """
        Test case for accounts_account_id_orders_get

        
        """
        pass

    def test_accounts_account_id_orders_orderid_area_codes_get(self):
        """
        Test case for accounts_account_id_orders_orderid_area_codes_get

        
        """
        pass

    def test_accounts_account_id_orders_orderid_get(self):
        """
        Test case for accounts_account_id_orders_orderid_get

        
        """
        pass

    def test_accounts_account_id_orders_orderid_history_get(self):
        """
        Test case for accounts_account_id_orders_orderid_history_get

        
        """
        pass

    def test_accounts_account_id_orders_orderid_notes_get(self):
        """
        Test case for accounts_account_id_orders_orderid_notes_get

        
        """
        pass

    def test_accounts_account_id_orders_orderid_notes_post(self):
        """
        Test case for accounts_account_id_orders_orderid_notes_post

        
        """
        pass

    def test_accounts_account_id_orders_orderid_npa_nxx_get(self):
        """
        Test case for accounts_account_id_orders_orderid_npa_nxx_get

        
        """
        pass

    def test_accounts_account_id_orders_orderid_put(self):
        """
        Test case for accounts_account_id_orders_orderid_put

        
        """
        pass

    def test_accounts_account_id_orders_orderid_tns_get(self):
        """
        Test case for accounts_account_id_orders_orderid_tns_get

        
        """
        pass

    def test_accounts_account_id_orders_orderid_totals_get(self):
        """
        Test case for accounts_account_id_orders_orderid_totals_get

        
        """
        pass

    def test_accounts_account_id_orders_post(self):
        """
        Test case for accounts_account_id_orders_post

        
        """
        pass

    def test_accounts_account_id_portins_get(self):
        """
        Test case for accounts_account_id_portins_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_activation_status_get(self):
        """
        Test case for accounts_account_id_portins_orderid_activation_status_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_activation_status_put(self):
        """
        Test case for accounts_account_id_portins_orderid_activation_status_put

        
        """
        pass

    def test_accounts_account_id_portins_orderid_area_codes_get(self):
        """
        Test case for accounts_account_id_portins_orderid_area_codes_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_delete(self):
        """
        Test case for accounts_account_id_portins_orderid_delete

        
        """
        pass

    def test_accounts_account_id_portins_orderid_get(self):
        """
        Test case for accounts_account_id_portins_orderid_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_history_get(self):
        """
        Test case for accounts_account_id_portins_orderid_history_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_fileid_delete(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_fileid_delete

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_fileid_get(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_fileid_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_fileid_metadata_delete(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_fileid_metadata_delete

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_fileid_metadata_get(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_fileid_metadata_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_fileid_metadata_put(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_fileid_metadata_put

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_fileid_put(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_fileid_put

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_get(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_loas_post(self):
        """
        Test case for accounts_account_id_portins_orderid_loas_post

        
        """
        pass

    def test_accounts_account_id_portins_orderid_notes_get(self):
        """
        Test case for accounts_account_id_portins_orderid_notes_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_notes_post(self):
        """
        Test case for accounts_account_id_portins_orderid_notes_post

        
        """
        pass

    def test_accounts_account_id_portins_orderid_npa_nxx_get(self):
        """
        Test case for accounts_account_id_portins_orderid_npa_nxx_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_put(self):
        """
        Test case for accounts_account_id_portins_orderid_put

        
        """
        pass

    def test_accounts_account_id_portins_orderid_tns_get(self):
        """
        Test case for accounts_account_id_portins_orderid_tns_get

        
        """
        pass

    def test_accounts_account_id_portins_orderid_totals_get(self):
        """
        Test case for accounts_account_id_portins_orderid_totals_get

        
        """
        pass

    def test_accounts_account_id_portins_post(self):
        """
        Test case for accounts_account_id_portins_post

        
        """
        pass

    def test_accounts_account_id_portins_totals_get(self):
        """
        Test case for accounts_account_id_portins_totals_get

        
        """
        pass

    def test_accounts_account_id_portouts_get(self):
        """
        Test case for accounts_account_id_portouts_get

        
        """
        pass

    def test_accounts_account_id_portouts_orderid_get(self):
        """
        Test case for accounts_account_id_portouts_orderid_get

        
        """
        pass

    def test_accounts_account_id_products_get(self):
        """
        Test case for accounts_account_id_products_get

        
        """
        pass

    def test_accounts_account_id_reports_get(self):
        """
        Test case for accounts_account_id_reports_get

        
        """
        pass

    def test_accounts_account_id_reports_instances_get(self):
        """
        Test case for accounts_account_id_reports_instances_get

        
        """
        pass

    def test_accounts_account_id_reports_reportid_get(self):
        """
        Test case for accounts_account_id_reports_reportid_get

        
        """
        pass

    def test_accounts_account_id_reports_reportid_instances_get(self):
        """
        Test case for accounts_account_id_reports_reportid_instances_get

        
        """
        pass

    def test_accounts_account_id_reports_reportid_instances_instance_id_file_get(self):
        """
        Test case for accounts_account_id_reports_reportid_instances_instance_id_file_get

        
        """
        pass

    def test_accounts_account_id_reports_reportid_instances_instance_id_get(self):
        """
        Test case for accounts_account_id_reports_reportid_instances_instance_id_get

        
        """
        pass

    def test_accounts_account_id_reports_reportid_instances_post(self):
        """
        Test case for accounts_account_id_reports_reportid_instances_post

        
        """
        pass

    def test_accounts_account_id_sipcredentials_get(self):
        """
        Test case for accounts_account_id_sipcredentials_get

        
        """
        pass

    def test_accounts_account_id_sipcredentials_post(self):
        """
        Test case for accounts_account_id_sipcredentials_post

        
        """
        pass

    def test_accounts_account_id_sipcredentials_user_name_delete(self):
        """
        Test case for accounts_account_id_sipcredentials_user_name_delete

        
        """
        pass

    def test_accounts_account_id_sipcredentials_user_name_get(self):
        """
        Test case for accounts_account_id_sipcredentials_user_name_get

        
        """
        pass

    def test_accounts_account_id_sipcredentials_user_name_put(self):
        """
        Test case for accounts_account_id_sipcredentials_user_name_put

        
        """
        pass

    def test_accounts_account_id_sites_get(self):
        """
        Test case for accounts_account_id_sites_get

        
        """
        pass

    def test_accounts_account_id_sites_post(self):
        """
        Test case for accounts_account_id_sites_post

        
        """
        pass

    def test_accounts_account_id_sites_site_id_delete(self):
        """
        Test case for accounts_account_id_sites_site_id_delete

        
        """
        pass

    def test_accounts_account_id_sites_site_id_get(self):
        """
        Test case for accounts_account_id_sites_site_id_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_inservice_numbers_get(self):
        """
        Test case for accounts_account_id_sites_site_id_inservice_numbers_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_orders_get(self):
        """
        Test case for accounts_account_id_sites_site_id_orders_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_orders_orderid_get(self):
        """
        Test case for accounts_account_id_sites_site_id_orders_orderid_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_orders_orderid_tns_get(self):
        """
        Test case for accounts_account_id_sites_site_id_orders_orderid_tns_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_portins_get(self):
        """
        Test case for accounts_account_id_sites_site_id_portins_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_put(self):
        """
        Test case for accounts_account_id_sites_site_id_put

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_get(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_post(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_post

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_delete(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_delete

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_get(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_movetns_post(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_movetns_post

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_put(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_put

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_tns_get(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_tns_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_tns_tn_get(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_tns_tn_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_tns_tn_put(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_tns_tn_put

        
        """
        pass

    def test_accounts_account_id_sites_site_id_sippeers_sippeer_id_totaltns_get(self):
        """
        Test case for accounts_account_id_sites_site_id_sippeers_sippeer_id_totaltns_get

        
        """
        pass

    def test_accounts_account_id_sites_site_id_totaltns_get(self):
        """
        Test case for accounts_account_id_sites_site_id_totaltns_get

        
        """
        pass

    def test_accounts_account_id_subscriptions_get(self):
        """
        Test case for accounts_account_id_subscriptions_get

        
        """
        pass

    def test_accounts_account_id_subscriptions_post(self):
        """
        Test case for accounts_account_id_subscriptions_post

        
        """
        pass

    def test_accounts_account_id_subscriptions_subscriptionid_delete(self):
        """
        Test case for accounts_account_id_subscriptions_subscriptionid_delete

        
        """
        pass

    def test_accounts_account_id_subscriptions_subscriptionid_get(self):
        """
        Test case for accounts_account_id_subscriptions_subscriptionid_get

        
        """
        pass

    def test_accounts_account_id_subscriptions_subscriptionid_put(self):
        """
        Test case for accounts_account_id_subscriptions_subscriptionid_put

        
        """
        pass

    def test_accounts_account_id_tnoptions_get(self):
        """
        Test case for accounts_account_id_tnoptions_get

        
        """
        pass

    def test_accounts_account_id_tnoptions_orderid_get(self):
        """
        Test case for accounts_account_id_tnoptions_orderid_get

        
        """
        pass

    def test_accounts_account_id_tnoptions_orderid_history_get(self):
        """
        Test case for accounts_account_id_tnoptions_orderid_history_get

        
        """
        pass

    def test_accounts_account_id_tnoptions_post(self):
        """
        Test case for accounts_account_id_tnoptions_post

        
        """
        pass

    def test_accounts_account_id_tnreservation_post(self):
        """
        Test case for accounts_account_id_tnreservation_post

        
        """
        pass

    def test_accounts_account_id_tnreservation_reservationid_delete(self):
        """
        Test case for accounts_account_id_tnreservation_reservationid_delete

        
        """
        pass

    def test_accounts_account_id_tnreservation_reservationid_get(self):
        """
        Test case for accounts_account_id_tnreservation_reservationid_get

        
        """
        pass

    def test_accounts_account_id_users_get(self):
        """
        Test case for accounts_account_id_users_get

        
        """
        pass

    def test_callbacks_notification_callback_api_post(self):
        """
        Test case for callbacks_notification_callback_api_post

        
        """
        pass

    def test_callbacks_port_out_validation_callback_api_post(self):
        """
        Test case for callbacks_port_out_validation_callback_api_post

        
        """
        pass

    def test_cities_get(self):
        """
        Test case for cities_get

        
        """
        pass

    def test_covered_rate_centers_get(self):
        """
        Test case for covered_rate_centers_get

        
        """
        pass

    def test_covered_rate_centers_rate_center_id_get(self):
        """
        Test case for covered_rate_centers_rate_center_id_get

        
        """
        pass

    def test_rate_centers_get(self):
        """
        Test case for rate_centers_get

        
        """
        pass

    def test_tns_get(self):
        """
        Test case for tns_get

        
        """
        pass

    def test_tns_tn_get(self):
        """
        Test case for tns_tn_get

        
        """
        pass

    def test_tns_tn_history_get(self):
        """
        Test case for tns_tn_history_get

        
        """
        pass

    def test_tns_tn_lata_get(self):
        """
        Test case for tns_tn_lata_get

        
        """
        pass

    def test_tns_tn_lca_get(self):
        """
        Test case for tns_tn_lca_get

        
        """
        pass

    def test_tns_tn_ratecenter_get(self):
        """
        Test case for tns_tn_ratecenter_get

        
        """
        pass

    def test_tns_tn_sippeers_get(self):
        """
        Test case for tns_tn_sippeers_get

        
        """
        pass

    def test_tns_tn_sites_get(self):
        """
        Test case for tns_tn_sites_get

        
        """
        pass

    def test_tns_tn_tndetails_get(self):
        """
        Test case for tns_tn_tndetails_get

        
        """
        pass

    def test_tns_tn_tnreservation_get(self):
        """
        Test case for tns_tn_tnreservation_get

        
        """
        pass

    def test_users_userid_get(self):
        """
        Test case for users_userid_get

        
        """
        pass

    def test_users_userid_password_put(self):
        """
        Test case for users_userid_password_put

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
